Traceback (most recent call last):
  File "/Users/joe/opt/anaconda3/envs/KLSN/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/joe/opt/anaconda3/envs/KLSN/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/joe/opt/anaconda3/envs/KLSN/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/joe/opt/anaconda3/envs/KLSN/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/joe/opt/anaconda3/envs/KLSN/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/joe/opt/anaconda3/envs/KLSN/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/joe/opt/anaconda3/envs/KLSN/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/joe/opt/anaconda3/envs/KLSN/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
flavor = Flavor.NU_E_BAR

fig, ax = plt.subplots(1,1, figsize=(10,5), tight_layout=True, facecolor='white')


ax.plot(fornax.time, fornax.luminosity[flavor].to('1e53 erg/s'), label='Fornax', color='darkorange')
ax.plot(kuroda.time, kuroda.luminosity[flavor].to('1e53 erg/s'), label='Kuroda', color='purple')
ax.plot(tamborra.time, tamborra.luminosity[flavor].to('1e53 erg/s'), label='Tamborra', color='darkgreen')
ax.plot(warren.time, warren.luminosity[flavor].to('1e53 erg/s'), label='Warren', color='magenta', linestyle='dashed')
ax.plot(nakazato.time, nakazato.luminosity[flavor].to('1e53 erg/s'), label='Nakazato', color='blue', linestyle='dashed')

ax.set(xscale='log',
       xlim=(5e-3, 12),
       xlabel='Time [s]',
       ylabel='Luminosity [$10^{53}$ erg s$^{-1}$]',
       title='20 $M_\odot$ progenitors')
ax.grid(ls=':', which='both')
ax.legend(bbox_to_anchor=(1.05, 1.0), loc='upper left')
plt.savefig('../out/plots/m20-initial', dpi=600)
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m/var/folders/bs/t_j9r03n3h39lmjyz9hr6b540000gn/T/ipykernel_53486/3277578282.py[0m in [0;36m<module>[0;34m[0m
[1;32m     17[0m [0max[0m[0;34m.[0m[0mgrid[0m[0;34m([0m[0mls[0m[0;34m=[0m[0;34m':'[0m[0;34m,[0m [0mwhich[0m[0;34m=[0m[0;34m'both'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     18[0m [0max[0m[0;34m.[0m[0mlegend[0m[0;34m([0m[0mbbox_to_anchor[0m[0;34m=[0m[0;34m([0m[0;36m1.05[0m[0;34m,[0m [0;36m1.0[0m[0;34m)[0m[0;34m,[0m [0mloc[0m[0;34m=[0m[0;34m'upper left'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 19[0;31m [0mplt[0m[0;34m.[0m[0msavefig[0m[0;34m([0m[0;34m'../out/plots/m20-initial'[0m[0;34m,[0m [0mdpi[0m[0;34m=[0m[0;36m600[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     20[0m [0mplt[0m[0;34m.[0m[0mshow[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/KLSN/lib/python3.8/site-packages/matplotlib/pyplot.py[0m in [0;36msavefig[0;34m(*args, **kwargs)[0m
[1;32m    964[0m [0;32mdef[0m [0msavefig[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    965[0m     [0mfig[0m [0;34m=[0m [0mgcf[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 966[0;31m     [0mres[0m [0;34m=[0m [0mfig[0m[0;34m.[0m[0msavefig[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    967[0m     [0mfig[0m[0;34m.[0m[0mcanvas[0m[0;34m.[0m[0mdraw_idle[0m[0;34m([0m[0;34m)[0m   [0;31m# need this if 'transparent=True' to reset colors[0m[0;34m[0m[0;34m[0m[0m
[1;32m    968[0m     [0;32mreturn[0m [0mres[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/KLSN/lib/python3.8/site-packages/matplotlib/figure.py[0m in [0;36msavefig[0;34m(self, fname, transparent, **kwargs)[0m
[1;32m   3003[0m                 [0mpatch[0m[0;34m.[0m[0mset_edgecolor[0m[0;34m([0m[0;34m'none'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   3004[0m [0;34m[0m[0m
[0;32m-> 3005[0;31m         [0mself[0m[0;34m.[0m[0mcanvas[0m[0;34m.[0m[0mprint_figure[0m[0;34m([0m[0mfname[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   3006[0m [0;34m[0m[0m
[1;32m   3007[0m         [0;32mif[0m [0mtransparent[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/KLSN/lib/python3.8/site-packages/matplotlib/backend_bases.py[0m in [0;36mprint_figure[0;34m(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)[0m
[1;32m   2253[0m                 [0;31m# force the figure dpi to 72), so we need to set it again here.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2254[0m                 [0;32mwith[0m [0mcbook[0m[0;34m.[0m[0m_setattr_cm[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mfigure[0m[0;34m,[0m [0mdpi[0m[0;34m=[0m[0mdpi[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 2255[0;31m                     result = print_method(
[0m[1;32m   2256[0m                         [0mfilename[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2257[0m                         [0mfacecolor[0m[0;34m=[0m[0mfacecolor[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/KLSN/lib/python3.8/site-packages/matplotlib/backend_bases.py[0m in [0;36mwrapper[0;34m(*args, **kwargs)[0m
[1;32m   1667[0m             [0mkwargs[0m[0;34m.[0m[0mpop[0m[0;34m([0m[0marg[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1668[0m [0;34m[0m[0m
[0;32m-> 1669[0;31m         [0;32mreturn[0m [0mfunc[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1670[0m [0;34m[0m[0m
[1;32m   1671[0m     [0;32mreturn[0m [0mwrapper[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/KLSN/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py[0m in [0;36mprint_png[0;34m(self, filename_or_obj, metadata, pil_kwargs, *args)[0m
[1;32m    507[0m         """
[1;32m    508[0m         [0mFigureCanvasAgg[0m[0;34m.[0m[0mdraw[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 509[0;31m         mpl.image.imsave(
[0m[1;32m    510[0m             [0mfilename_or_obj[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0mbuffer_rgba[0m[0;34m([0m[0;34m)[0m[0;34m,[0m [0mformat[0m[0;34m=[0m[0;34m"png"[0m[0;34m,[0m [0morigin[0m[0;34m=[0m[0;34m"upper"[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    511[0m             dpi=self.figure.dpi, metadata=metadata, pil_kwargs=pil_kwargs)

[0;32m~/opt/anaconda3/envs/KLSN/lib/python3.8/site-packages/matplotlib/image.py[0m in [0;36mimsave[0;34m(fname, arr, vmin, vmax, cmap, format, origin, dpi, metadata, pil_kwargs)[0m
[1;32m   1614[0m         [0mpil_kwargs[0m[0;34m.[0m[0msetdefault[0m[0;34m([0m[0;34m"format"[0m[0;34m,[0m [0mformat[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1615[0m         [0mpil_kwargs[0m[0;34m.[0m[0msetdefault[0m[0;34m([0m[0;34m"dpi"[0m[0;34m,[0m [0;34m([0m[0mdpi[0m[0;34m,[0m [0mdpi[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1616[0;31m         [0mimage[0m[0;34m.[0m[0msave[0m[0;34m([0m[0mfname[0m[0;34m,[0m [0;34m**[0m[0mpil_kwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1617[0m [0;34m[0m[0m
[1;32m   1618[0m [0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/KLSN/lib/python3.8/site-packages/PIL/Image.py[0m in [0;36msave[0;34m(self, fp, format, **params)[0m
[1;32m   2230[0m                 [0mfp[0m [0;34m=[0m [0mbuiltins[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0mfilename[0m[0;34m,[0m [0;34m"r+b"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2231[0m             [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 2232[0;31m                 [0mfp[0m [0;34m=[0m [0mbuiltins[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0mfilename[0m[0;34m,[0m [0;34m"w+b"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2233[0m [0;34m[0m[0m
[1;32m   2234[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../out/plots/m20-initial.png'
FileNotFoundError: [Errno 2] No such file or directory: '../out/plots/m20-initial.png'

